#!/bin/bash
gn=groupname
#gmin=GID_MIN=1120
#gmax=GID_MAX=1130
for server in `cat /tmp//scripts/AddorDell/servers`
do
		for gn in `cat /tmp/scripts/AddorDell/groupids`
		do
		echo ----------------------------------------
		echo DELETING $gn FROM $server...
		ssh $server groupdel $gn
		echo Successfully DELETED $gn FROM $server
		echo ----------------------------------------
		done
done
